server:
  port: 8208
  tomcat:
    connection-timeout: 7200000
  forward-headers-strategy: framework
  servlet:
      context-path: /api

spring:
  mvc:
    async:
      request-timeout: 7200000
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: spring-ai-functions

#Pass API key as environment variable, e.g. -DAI_API_KEY=your-api-key
ai:
  api-key: ${AI_API_KEY}
  base-url: https://api.together.xyz/v1
  model-name: meta-llama/Llama-3.2-90B-Vision-Instruct-Turbo

#Swagger
springdoc:
  api-docs:
    path: /docs

#Logging levels
logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.springframework.security.authentication: INFO
    org.springframework.boot: INFO
    org.springframework.ws: WARN
    org.springframework.web.socket.config.WebSocketMessageBrokerStats: WARN
    com.museum.ai: DEBUG